### PR TITLE
Php8.2

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by farvardin** [comment]
@ericgaspar I didn't notice you've also added an upgrade to php 8.2. The problem is lionwiki is not compatible with php 8.2. It works with 8.1 (but with a few problems), and the best is with php 7.4

After the upgrade, the home page of the wiki is totally blank (the linter test cannot see this it seems). I'll reverse it to php 7.4 because it breaks all current installations.

**Comment by farvardin** [comment]
it's a plugin located into ``plugins`` which causes the error, I'm investigating it

**Comment by farvardin** [comment]
it should be fixed now

**Comment by farvardin** [comment]
there are still problems with php8.2, requiring users to manually update some configuration files. It's better to stay with php7.4

**Pull request merged**
