### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by tituspijean**
## Problem

- App is failing automated tests

## Solution

- Fix permissions, remove access to other users

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by farvardin** [comment]
@tituspijean 
it seems to crash because the upgrade tests for the checksums, maybe this part?

```
ynh_backup_if_checksum_is_different --file="$final_path/config.php"
ynh_backup_if_checksum_is_different --file="$final_path/config.t2t"
ynh_backup_if_checksum_is_different --file="$final_path/menu.php"
```

If I don't use this, users might encounter data loss: their configuration will be overwritten upon upgrade, which is bad.

**Comment by tituspijean** [comment]
@farvardin the warning is definitely to be addressed, but I think what's making the script fail is the warning right after that;

`/usr/share/yunohost/helpers.d/backup: line 257: YNH_BACKUP_DIR: unbound variable`.
@alexAubin, are we hitting an edge case where this variable is somehow not initialized in the `restore` script?

**Comment by alexAubin** [comment]
@tituspijean @farvardin : the script tried to call ynh_restore_file during the upgrade, which only works in the context of the restore script ... : https://github.com/YunoHost-Apps/lionwiki-t2t_ynh/blob/fix/scripts/upgrade#L121

I'm not sure to understand the indention, nor what's the intention of the three `ynh_backup_if_checksum_is_different` and `ynh_store_file_checksum` at the end of the upgrade ...

**Comment by farvardin** [comment]
> @tituspijean @farvardin : the script tried to call ynh_restore_file during the upgrade, which only works in the context of the restore script ... : https://github.com/YunoHost-Apps/lionwiki-t2t_ynh/blob/fix/scripts/upgrade#L121
> 
> I'm not sure to understand the indention, nor what's the intention of the three `ynh_backup_if_checksum_is_different` and `ynh_store_file_checksum` at the end of the upgrade ...

the package is shipping some configuration and default files (the homepage of the wifi for example). In the case the user has modified some of them, the upgrade would replace them by the default values. I don't know how to achieve that, but I'll check how other packages are handling this...

**Pull request merged**
